# Generated by Django 5.0.6 on 2024-06-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='str_time',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
